# Generated by Django 3.1.14 on 2025-03-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_auto_20250313_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(blank=True, default='default_pokemon.png', null=True, upload_to='pokemon_images', verbose_name='Изображение'),
        ),
    ]
